name: Run Jest Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: Google ChromeOS
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test